################################
# Genetic algorithm parameters #
################################

population_size: 200              # Default: 200
mutation_probability: 0.05        # Default: 0.05 (5%)
mutation_standard_deviation: 0.3  # Default: 0.3
elitism: True                     # Default: True
stop_condition:
  generations: .inf               # Default: .inf / Max number of generations to evolve
  score: .inf                     # Default: .inf / Max score
  time: .inf                      # Default: .inf / Max training time in seconds
save_best: True                   # Default: True / Saves the best model in a .pth file
load_previous_best: True          # Default: True / Loads the best (saved in .pth file) and mutated variations as generation 1

# Note: By removing or misspelling any of the parameters, a default value will be assumed